name: SSH and Git Pull

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into the server and pull changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/pemira && \
            sudo git config --local user.name ${{ secrets.GITHUB_USERNAME }} && \
            sudo git config --local user.email ${{ secrets.GITHUB_EMAIL }} && \
            sudo git pull

      - name: Restart Nginx
        run: sudo systemctl restart nginx

